batch_size: 128
epoch: 30
learning rate: 0.0002
lr_update: 15
optimizer: Adam
margin: 0.2
word_dim: 300
embed_size: 1024
grad_clip: 2
crop_size: 224
num_layers: 1
max_violation: true
img_dim: 4096
workers: 1
log_step: 200
val_step: 500
cnn_type: "vgg19"
use_abs: false
no_imgnorm: false
seed: 123
device_id: 7
device_target: "Ascend"
data_path: "data"
data_name: "f30k_precomp"
vocab_path: "./vocab/"
num_epochs: 30
use_restval: false
enable_modelarts: false
finetune: false
ckpt_file: "./best.ckpt"
vocab_size: 8481
file_name: "model"
file_format: "MINDIR"